### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by JesusMtnez** [HKey/el-init#16]
Hi,

I really like the idea of this project, I would like to use it for my [`emacs.d`](https://gitlab.com/JesusMtnez/emacs.d). But I want to know if the project is still active. I see there aren't changes since 2016. Also, there is no CI integration with emacs 25.3 and latest 26.1. 

What I really mean is I would really like to start using this package and contribute if necessary if the project is still active before making my own loading system.

Thanks for all the hard work!

**Comment by HKey** [comment]
Hello

I'm sorry for my late reply.  

> I really like the idea of this project, I would like to use it for my emacs.d.  

I'm glad to hear that and thank you for using el-init. I'm happy!

> But I want to know if the project is still active. I see there aren't changes since 2016. Also, there is no CI integration with emacs 25.3 and latest 26.1.

This project is still active.
It's my lazinnes that the emacs versions for CI haven't been updated in this 2 years.

I'll update them  soon.

Thanks.

**Comment by HKey** [comment]
I've updated the emacs versions for CI. #17

**Comment by JesusMtnez** [comment]
Thank you so much! I've been using this package on my `emacs.d` since I opened this issue and it's been a pleasure
